"""empty message

Revision ID: 051a46489510
Revises: 74433eb9c7cf
Create Date: 2025-01-27 15:20:52.041911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051a46489510'
down_revision = '74433eb9c7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker', schema=None) as batch_op:
        batch_op.drop_column('trading_symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trading_symbol', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
