"""empty message

Revision ID: 3d015e812061
Revises: 051a46489510
Create Date: 2025-01-29 03:28:18.677230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d015e812061'
down_revision = '051a46489510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=20), nullable=False))

    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
